# Site settings
title: Steven's Blog
email: zj299792458@live.com
description: > # this means to ignore newlines until "baseurl:"
  Steven Personal Blog
baseurl: "/StevenPersonalBlog" # the subpath of your site, e.g. /blog/
url: "https://zj299792458.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  zj299792458

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

theme: jekyll-theme-merlot